# fly.toml app configuration file generated for xmtp-simple-pin-server on 2023-09-26T14:03:14-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-builder-floral-bush-9350"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
